name: Unit Tests Pass (Fast)

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  build:
    runs-on: ubuntu-latest
    uses: marcuscastelo/vscode-anime/.github/workflows/compile_lint.yml@meta/ci

  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: npm run test