name: Unit Tests Pass (Fast)

on:
  workflow_dispatch:
  
jobs:
  build:
    uses: marcastelo/vscode-anime/.github/workflows/compile_lint.yml@main
    runs-on: ubuntu-latest

  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: npm run test