name: Unit Tests Pass (Fast)

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  build-and-lint:
    uses: marcuscastelo/vscode-anime/.github/workflows/compile_lint.yml@meta/ci

  tests:
    runs-on: ubuntu-latest
    needs: build-and-lint
    steps:
      - uses: actions/checkout@v3
      - run: npm run test