name: Unit Tests Pass (Fast)

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  tests:
    uses: marcastelo/vscode-anime/.github/workflows/compile_lint.yml@main
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: npm run test